server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:C:\Users\logonrmlocal\Desktop\SpringFiap;DB_CLOSE_ON_EXIT=false
    username: fiap
    password: fiap
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    user:
      password: password
      name: admin
      roles: ADMIN
jwt:
  secret: F14ps3cr3t
  expiration: 1
